/* ===================================================
   tinyVue 1.0 — Application Data
   All data from cv.json, projects.json, multimedia.json, services.json
   Inlined as plain JS object — zero JSON fetches needed
   =================================================== */

const DATA = {
  personal: {
    name: "Md. Asaduzzaman",
    nickname: "Aminur",
    title: "IT & Digital Operations Specialist",
    phone1: "+880 1979 670601",
    phone2: "+880 1719 670601",
    email: "amin670bd@gmail.com",
    email2: "amin670job@gmail.com",
    location: "Ashuliya, Savar, Dhaka, Bangladesh",
    linkedin: "linkedin.com/in/aminur670bd",
    website: "https://amin670bd.github.io",
    photo: "assets/images/profile.webp",
    dob: "22/01/1997",
    blood: "O+",
    religion: "Islam",
    currentSalary: "21,800 BDT",
    expectedSalary: "Negotiable",
    available: "Immediately"
  },
  languages: [
    { name: "Bangla", level: "Native", pct: 100 },
    { name: "English", level: "Fluent", pct: 85 },
    { name: "Hindi", level: "Intermediate", pct: 60 }
  ],
  objective: "I offer a unique blend of creative, technical, and support-based services that span across IT support, ERP operations, digital systems, and administrative workflows. My goal is to contribute to a company's IT infrastructure with hands-on experience in system maintenance, user support, and process improvement.",
  summary: "IT professional since 2018 with 6.5+ years of hands-on employment across IT support, ERP systems, web development, and system integration. Skilled in troubleshooting, hardware/software setup, ERP data entry, and user support. Adept at managing in-house workflows, enhancing digital visibility, and ensuring smooth technical and administrative operations.",
  stats: [
    { value: "15+", label: "Sites Built" },
    { value: "60%", label: "Efficiency Boost" },
    { value: "100+", label: "Users Managed" }
  ],
  skills: [
    { title: "Office & Productivity", icon: "description", items: ["MS Office (Word, Excel, PowerPoint, Outlook)", "Google Workspace", "Excel Automation & Macros", "Report Generation", "PDF Editing"] },
    { title: "Design & Graphics", icon: "palette", items: ["Photoshop", "Illustrator", "Canva", "Infographics", "Posters / Labels", "Logos", "Invoices"] },
    { title: "Video & AI Multimedia", icon: "movie", items: ["Filmora (Video Editing)", "AI Image Manipulation & Editing", "AI Audio & Multimedia"] },
    { title: "ERP & Business Systems", icon: "storage", items: ["GPRO ERP (All Modules)", "Inventory Management", "Payroll / Billing", "Data Entry & Verification", "POS Systems", "File Handling", "ERP Install & Support", "Garments Systems", "RFID Tag Generation"] },
    { title: "E-Commerce & Marketplaces", icon: "shopping_cart", items: ["Product Listing", "Order / Shipping Handling", "Customer Support", "Bundle Tracking", "Amazon Seller Central", "eBay", "WooCommerce", "WordPress"] },
    { title: "C / C++ & .NET Stack", icon: "code", items: ["C / C++", "C# & WinForms", ".NET SDK 9/10", "ADO.NET", "Crystal Reports", ".NET Framework", "MS Access"] },
    { title: "PHP & Laravel Stack", icon: "code", items: ["Laravel", "Blade Templates", "Eloquent ORM", "Artisan CLI", "REST APIs", "MVC Architecture", "PHP & MySQL", "PDO"] },
    { title: "Frontend Stack", icon: "code", items: ["Vue 3 (Options / Composition API)", "Vue Router", "Pinia", "Vite", "HTML / CSS / JavaScript", "Tailwind / Bootstrap 4/5", "jQuery", "Responsive Design"] },
    { title: "Databases & SQL", icon: "table_chart", items: ["MySQL / phpMyAdmin", "MySQL Workbench", "SQL Server", "MS Access", "Excel VBA Macros"] },
    { title: "AI & Automation Tools", icon: "smart_toy", items: ["Prompt Engineering", "GitHub Copilot", "ChatGPT", "Opencode / OpenRouter", "Qwen AI / Gemini", "n8n Workflow Automation"] },
    { title: "Web Dev & CMS", icon: "travel_explore", items: ["WordPress", "Elementor", "WooCommerce", "LMS", "Plugin Dev", "Payment Systems", "ACF", "Custom Post Types", "REST API", "Child Themes", "SEO Plugins"] },
    { title: "IT Support & System Admin", icon: "dns", items: ["Windows / Linux OS Install", "Hard / Soft Diagnostics", "Remote IT Support", "System Maintenance", "User Training", "Driver Setup", "PC Assembly & Upgrade"] },
    { title: "System Integration & Hardware", icon: "settings_ethernet", items: ["Barcode Printer Configuration", "Automated Label Printing", "Weight Scale Integration", "NXP MCU RFID Terminals", "MOXA Serial Cards", "Network Configuration"] },
    { title: "Email & Communication", icon: "forward_to_inbox", items: ["Corporate Email Setup", "Bulk Mailing Tools", "Email Automation", "Face-to-Face Communication", "Social Media Management"] },
    { title: "Networking & Security", icon: "lan", items: ["IP Config & Subnetting", "LAN / Router Setup", "File / Printer Sharing", "Firewall & Antivirus", "IP Camera Installation", "Network Cabling", "RS-485 Cabling"] }
  ],
  experience: [
    { title: "Sr. Officer (In-Charge, Barcode)", company: "Dhaka Thai ALCOMAXX PLC", location: "Ashuliya, Savar, Dhaka", period: "Sep 2025 - Present", highlights: ["Lead barcode operations, product labeling, bundling, and production coordination across packing lines", "Developed and maintained C# desktop applications for weight scale integration with LightHouse ERP", "Troubleshot utility software, barcode printers, and IT systems across packing lines", "Improved workflow efficiency and reduced downtime through barcode system optimization", "Designed and implemented automated label printing systems increasing daily output from 2,500 to 8,000+ labels", "Coordinated with production and quality teams to ensure accurate product tracking and traceability"] },
    { title: "Officer - IT (G-Pro)", company: "Keya Cosmetic Ltd.", location: "Gazipur, Dhaka", period: "May 2022 - Jul 2025", highlights: ["Administered GPRO ERP modules including cutting, store, production, payroll, billing, and inventory management", "Configured IP settings and network cabling for 30+ production floor workstations", "Set up and maintained printer connectivity across the facility", "Installed and configured IP cameras for production floor surveillance", "Managed 30+ production lines each with 10+ NXP MCU-based RFID terminals as IoT checkpoints", "Configured and maintained MOXA multiport serial cards over RS-485 telephone-type cabling to collect data from RFID terminals into GPRO ERP", "Provided IT training and support to 30+ end-users on ERP modules and software tools", "Assisted with routine server backups and basic system maintenance", "Automated routine data entry and reporting tasks using Excel macros and ERP export tools"] },
    { title: "IT Assistant", company: "Rahamat Sweaters Ltd.", location: "Gazipur, Dhaka", period: "Jan 2022 - May 2022", highlights: ["Designed barcode and label systems for production tracking and warehouse management", "Performed ERP data entry, verification, and synchronization across multiple departments", "Provided hardware and software support for production floor workstations", "Assisted in inventory reconciliation and stock movement documentation"] },
    { title: "Web Developer", company: "Faith Media Ltd.", location: "Mohakhali, Dhaka", period: "Jan 2021 - Jul 2021", highlights: ["Developed and maintained WordPress/WooCommerce websites with custom themes and plugins", "Created SEO-optimized content, product listings, and competitive pricing strategies for e-commerce clients", "Designed infographics, promotional banners, and website visuals using Photoshop and Illustrator", "Implemented LMS and membership plugins for client educational platforms", "Optimized site performance through caching, image compression, and database optimization"] },
    { title: "Remote IT Assistant to CEO", company: "TIC Accessories Inc.", location: "New York, USA", period: "Jan 2020 - Dec 2020", highlights: ["Managed Amazon Seller Central and eBay Seller Hub — listings, pricing, inventory sync, and order processing for 200+ products", "Automated Excel reports and email marketing campaigns for sales and inventory tracking", "Provided remote IT support via AnyDesk and TeamViewer to New York office staff", "Created professional product photography and edited images for marketplace listings", "Monitored competitor pricing and adjusted listings to maintain competitive edge"] },
    { title: "ICT Teacher & IT Trainer", company: "EEE & IT Training Center", location: "Naogaon", period: "Jul 2019 - Dec 2019", highlights: ["Trained SSC and HSC students in MS Office, programming fundamentals, and hardware troubleshooting", "Developed practical IT curriculum modules with hands-on exercises for real-world skill building", "Guided students through computer assembly, OS installation, and basic networking labs", "Conducted assessments and provided one-on-one mentoring to improve student outcomes"] },
    { title: "IT Assistant", company: "ZSN Computers", location: "Naogaon", period: "Jul 2018 - Dec 2018", highlights: ["Assembled custom PCs and installed operating systems, drivers, and essential software", "Provided hardware diagnostics, repair services, and software troubleshooting for walk-in clients", "Maintained workshop inventory of components and managed customer service requests", "Performed system upgrades including RAM, storage, and graphics card installations"] }
  ],
  education: [
    { degree: "Diploma in Computer Engineering", school: "Bogura Polytechnic Institute", year: "2018", grade: "CGPA: 2.92 / 4.00", gradeValue: 2.92, gradeMax: 4, location: "Bogura", icon: "computer", skills: ["C Programming", "Python", "Java", "Web Development", "Database Management", "Computer Networking"], achievements: [{ text: "Res-Q & Remote Control — IoT-based rescue car for multi-sector demo missions | Champion at BPI Innovation & Projects Fair 2017", award: true }, { text: "B.P.I. Virtual Institute — Awarded at Zilla ICT Project Fair 2017", award: true }, { text: "Easy C IDE — Lightweight C compiler IDE with auto-save feature", award: false }, { text: "B.P.I. Innovation Lab — Hardware, software & network setup at BPI", award: false }] },
    { degree: "S.S.C. (Vocational, ICT)", school: "Naogaon Technical School & College", year: "2013", grade: "GPA: 4.88 / 5.00", gradeValue: 4.88, gradeMax: 5, location: "Naogaon", icon: "school", skills: ["Computer Application", "ICT", "Programming Basics", "Hardware Fundamentals"], achievements: [{ text: "ICT Lab Installation — PC setup & network config for Naogaon Technical School", award: false }, { text: "Practical training in MS Office, Computer Applications & Hardware", award: false }, { text: "GPA 4.88 / 5.00 — Outstanding academic performance", award: true }] }
  ],
  training: [
    { title: "Web Design & Development", topics: ["WordPress", "PHP", "MySQL", "HTML", "CSS", "JavaScript", "Bootstrap", "jQuery"], institution: "Bangladesh IT Institute, Dhaka", year: "2017", duration: "3 months", icon: "web" },
    { title: "Software Development", topics: ["Win-Forms", "C#.NET", "SQL Server"], institution: "Smart Softwares & Training Center, Bogura", year: "2016", duration: "6 months", icon: "code" },
    { title: "Graphics Design", topics: ["Photoshop", "Illustrator"], institution: "Rahim IT Solutions, Bogura", year: "2015", duration: "3 months", icon: "palette" },
    { title: "CompTIA A+", topics: ["Hardware", "Software", "IT-ICT", "MS Office"], institution: "Opurbo Computers & Training Center, Naogaon", year: "2013", duration: "6 months", icon: "settings" }
  ],
  achievementCategories: [
    { title: "Technical Impact", icon: "rocket_launch", color: "var(--primary)", items: [{ title: "YAOHUA Scale Desktop App", description: "Developed a desktop app for YAOHUA digital scale integration, reducing packing production time by 60% and tripling bundle QR label output from 2.5K to 8K+ daily." }, { title: "15+ Websites Built", description: "Developed 15+ responsive websites and e-commerce platforms using WordPress + Elementor." }, { title: "E-Commerce Listings Management", description: "Managed 200+ SEO-optimized product listings for Amazon, eBay, and WooCommerce." }] },
    { title: "Training & Leadership", icon: "school", color: "var(--accent-emerald)", items: [{ title: "ERP Module Training", description: "Administered and trained 30+ users on ERP modules including HR, Payroll, Store, Inventory." }, { title: "Student IT Education", description: "Delivered IT training to 80+ students on MS Office and system troubleshooting during session." }] },
    { title: "Awards & Recognition", icon: "emoji_events", color: "var(--accent-amber)", items: [{ title: "Res-Q — Champion", description: "BPI College Projects Fair 2017 — IoT-based rescue car for multi-sector demo missions." }, { title: "BPI Virtual Institute — Champion", description: "ICT Fair 2017, Bogura District & Rajshahi Division Level." }] }
  ],
  references: [
    { name: "Md. Mamunur Rashid", title: "Manager (IT, G-Pro)", company: "Keya Knit Composite Ltd.", phone: "01906-472201" },
    { name: "Md. Al Amin", title: "Sr. Officer (IT, G-Pro)", company: "Keya Knit Composite Ltd.", phone: "01521-447631" },
    { name: "Md. Abdur Rahim", title: "Head of Sales & Marketing", company: "Alpha.Net.Bd", phone: "01712-685203" },
    { name: "Md. Sagar Islam", title: "Production Coordinator", company: "Casual Garments Ltd.", phone: "01727-831168" },
    { name: "Md. Mamunur Rashid", title: "Manager (IT, G-Pro)", company: "Keya Knit Composite Ltd.", phone: "01906-472201" },
    { name: "Md. Al Amin", title: "Sr. Officer (IT, G-Pro)", company: "Keya Knit Composite Ltd.", phone: "01521-447631" },
    { name: "Md. Abdur Rahim", title: "Head of Sales & Marketing", company: "Alpha.Net.Bd", phone: "01712-685203" },
    { name: "Md. Sagar Islam", title: "Production Coordinator", company: "Casual Garments Ltd.", phone: "01727-831168" }
  ],
  media: {
    channelUrl: "https://www.youtube.com/@aminur670",
    channelHandle: "@aminur670",
    channelName: "Aminur670",
    channelAvatar: "https://yt3.ggpht.com/cNVM5rkUOhCpTkvrrF956fjyQB6eqlmLLP1Yt1kAiKKa64RGL9s6TUx-RjwgQOJ-jw7Bj25qHw=s88-c-k-c0x00ffffff-no-rj",
    description: "Creative content, tech projects, and more.",
    playlist: { id: "UU9ndhDLZxczY17jgLdDlx4g", title: "Channel Uploads" },
    featuredVideoId: "W3YmvF_gh8Q",
    links: [
      { title: "YouTube Channel", url: "https://www.youtube.com/@aminur670", icon: "smart_display" },
      { title: "Google Drive Portfolio", url: "#", icon: "cloud" }
    ]
  },
  menuItems: [
    { path: "/", label: "Home", icon: "home" },
    { path: "/about", label: "About", icon: "person" },
    { path: "/skills", label: "Skills", icon: "settings" },
    { path: "/experience", label: "Experience", icon: "work" },
    { path: "/education", label: "Education", icon: "school" },
    { path: "/projects", label: "Projects", icon: "folder_open" },
    { path: "/multimedia-works", label: "Multimedia Works", icon: "smart_display" },
    { path: "/achievements", label: "Achievements", icon: "emoji_events" },
    { path: "/services", label: "Services", icon: "handyman" },
    { path: "/contact", label: "Contact", icon: "email" }
  ],
  projectCategories: [
    { name: "Software Development", key: "software", icon: "laptop_mac", items: [
      { id: "weight-checker", title: "Aluminum Bundle Weight Checker V3/V4", tech: "C#.NET, Serial Port, ERP Automation", description: "Desktop application for automated bundle weight checking with serial port scale integration and ERP label printing.", date: "2026-04-01" },
      { id: "weight-scale", title: "YAOHUA Digital Weight Scale Integration", tech: "RS232, Serial Port, Hardware Integration", description: "Industrial hardware-software bridge connecting YAOHUA XK3190-D# weight indicators to LightHouse ERP.", date: "2025-02-01" },
      { id: "tuition-management", title: "Tuition Management System", tech: "C# & SQL Server Local DB", description: "Students information, fee management, batch management desktop application.", date: "2016-09-01" },
      { id: "tic-warehouse", title: "TIC Warehouse App", tech: "PHP & MySQL", description: "Basic Warehouse Inventory management software.", date: "2020-06-01" },
      { id: "auto-bell", title: "Auto Bell 2.0", tech: "VB.net & MS-AccessDB", description: "Automated bell system with Text-to-Speech for schools.", date: "2017-04-01" },
      { id: "easy-c-ide", title: "Easy C IDE", tech: "VB.net & Compiler", description: "Lightweight C IDE with auto-save feature.", date: "2016-03-01" },
      { id: "resq-remote", title: "Res-Q & Remote Control", tech: "C/C++, Arduino & C#", description: "Robotic car firmware and control desktop app. Champion at BPI College Projects Fair 2017.", date: "2017-03-01" },
      { id: "tasbih", title: "Tasbih - Digital Prayer Counter", tech: "MIT App Inventor", description: "Android app for digital tasbih (prayer bead) counting with multiple counter profiles and history tracking.", date: "2024-10-01" },
      { id: "zenbreaths", title: "ZenBreaths - Guided Breathing App", tech: "HTML, Tailwind CSS, Vue 3, Nuxt, Capacitor", description: "Meditation and guided breathing exercise app with customizable session durations and visual cues.", date: "2024-12-01" },
      { id: "dtl-google-chrome", title: "DTL - Portable Google Chrome (No CORS)", tech: "Portable Chrome, Batch Scripting, CORS Bypass", description: "Configured a portable Google Chrome browser with custom user data directory enabling no-CORS development/testing environment for internal web applications.", date: "2026-05-01" }
    ]},
    { name: "Web & E-Commerce", key: "web", icon: "language", items: [
      { id: "faith-it", title: "Faith IT - Agency Portfolio", tech: "WordPress, Elementor", description: "Agency Portfolio website for Faith Media Ltd.", date: "2020-02-01" },
      { id: "gontobbo-express", title: "Gontobbo Express", tech: "WordPress, WooCommerce", description: "Logistics platform implementation.", date: "2021-01-01" },
      { id: "chembynavid", title: "ChemByNavid", tech: "WordPress, WooCommerce, LMS", description: "Payment, LMS, Content Update integration.", date: "2021-02-15" },
      { id: "rapid-supplies", title: "Rapid Supplies Inc.", tech: "WordPress, WooCommerce", description: "Tech e-commerce for TIC Accessories.", date: "2020-07-01" },
      { id: "tic-website", title: "TIC Accessories - Main Company Website", tech: "WordPress, Elementor, WooCommerce", description: "Full WordPress company website with product catalog, service pages, and contact system for TIC Accessories Inc.", date: "2020-03-01" },
      { id: "different-cafe", title: "DifferentCafeBD", tech: "WordPress, Elementor", description: "Cafe brand website with menu, online ordering & local SEO.", date: "2021-02-20" },
      { id: "realcafe-bd", title: "RealCafeBd", tech: "WordPress, Elementor", description: "Cafe brand website with menu, online ordering & local SEO.", date: "2021-02-26" },
      { id: "cosmicshopbd", title: "CosmicShopBd", tech: "WordPress, WooCommerce, Android, Java, REST API", description: "Retail/wholesale online store with Android app.", date: "2024-09-01" },
      { id: "hakimadapp-website", title: "Hakimadapp.github.io - Religious Website", tech: "HTML, CSS, JavaScript, GitHub Pages", description: "Faith-based religious website hosted on GitHub Pages.", date: "2026-03-01" }
    ]},
    { name: "IT Support & Maintenance", key: "it", icon: "build", items: [
      { id: "dhakathai-it", title: "DhakaThai Alcomaxx PLC", tech: "IT Support, OS, Barcode ERP", description: "IT Support, OS, Barcode ERP, Maintenance, Tools Development - full IT operations for aluminum manufacturing plant.", date: "2023-08-01" },
      { id: "keya-group-it", title: "Keya Group [IT-GPRO]", tech: "GPRO ERP, IT Support, RFID", description: "IT Support, OS, ERP, Maintenance, RJ-6 MOXA Network & Devices Management - GPRO ERP administration across all modules, IT support for 30+ production floor workstations.", date: "2022-05-22" },
      { id: "tic-accessories", title: "TIC Accessories Inc. - Full-Spectrum Support", tech: "WordPress, E-Commerce, IT Support", description: "Remote IT support, WordPress website, WooCommerce e-commerce, Amazon/eBay listings, product photography, infographics, and digital operations for New-York based tech accessories company.", date: "2020-02-01" },
      { id: "bpi-lab", title: "B. P. I. Innovation Lab", tech: "Hardware, Software, Network Setup", description: "Software, hardware, and network setup for college innovation lab.", date: "2018-03-01" },
      { id: "naogaon-lab", title: "Naogaon Tech. School Lab", tech: "PC Assembly, OS Install", description: "PC software/hardware setup and ICT lab installation for technical school.", date: "2012-09-01" }
    ]},
    { name: "Graphics & Design", key: "design", icon: "palette", items: [
      { id: "amazon-ebay-listings", title: "Amazon/eBay Product Listings (200+ Listings)", tech: "Photoshop, Illustrator, SEO, Amazon Seller Central", description: "Designed and optimized 200+ SEO-friendly product listings for Amazon and eBay marketplaces.", date: "2020-01-01" },
      { id: "infographic-banner", title: "Infographic & Banner Design", tech: "Photoshop, Illustrator, Canva, Filmora", description: "Created sales banners, promotional infographics, and social media visuals for e-commerce brands.", date: "2020-04-01" },
      { id: "label-packaging", title: "Product Label & Packaging Design", tech: "Photoshop, Illustrator, Barcode Systems", description: "Designed product labels, barcode labels, and packaging materials for industrial and retail products.", date: "2025-10-01" },
      { id: "barcode-label-system", title: "Barcode & QR Label Systems", tech: "Label Design, ERP Integration, Barcode Printers", description: "Designed and implemented barcode and QR label systems for ERP-integrated production and warehouse workflows.", date: "2025-10-01" }
    ]}
  ],
  featuredProject: { id: "weight-checker", title: "Digital Weight Scale & Weight Checker App", company: "DhakaThai AlcoMaxx PLC", tech: "C#.NET, Serial Port Integration, ERP Automation", description: "Designed and developed a custom desktop application to integrate physical weight meters/scales with LightHouse ERP at the Packing Section.", images: ["assets/images/projects/weight-checker/weight_checker_v4.png", "assets/images/projects/weight-checker/weight_checker_v4.4.png", "assets/images/projects/weight-checker/weight_scale.png"], details: ["Integrated physical weight meters with LightHouse ERP via Serial Port communication", "Automated bundle packing workflow, reducing packing time by 60%", "Scaled daily label output from 2,500 to 8,000+ labels", "Delivered robust solution improving operational efficiency and minimizing manual errors"], date: "2025-06-01" },
  projectDetails: {
    "weight-checker": { title: "Aluminum Bundle Weight Checker V3.0", subtitle: "Industrial Integration Suite & ERP Sync Solution", company: "DhakaThai AlcoMaxx PLC", developer: "Md. Asaduzzaman (Aminur)", tech: ["C#.NET", "Serial Port Integration", "ERP Automation", "RS232 Protocol", "CSV Data Engine"], images: ["assets/images/projects/weight-checker/weight_checker_v4.png", "assets/images/projects/weight-checker/weight_checker_v4.4.png", "assets/images/projects/weight-checker/weight_scale.png"], metrics: [{ value: "70%", label: "Reduced Time Bottlenecks" }, { value: "8,000+", label: "Daily Bundle Labels" }, { value: "Real-time", label: "RS232 → ERP" }, { value: "100%", label: "Correct Weight in ERP" }], abstract: "Designed and developed a console-based high-precision automation suite for industrial aluminum production.", flow: [{ icon: "storage", title: "System Initialization", text: "The engine dynamically parses WEIGHT_CHART_MASTER.csv into a high-speed memory dictionary for O(1) instant lookup of 1,500+ Die profiles." }, { icon: "memory", title: "Industrial Scale Bridge", text: "Implements a 200ms polling cycle on Scale I/O file X:\\wbdata1.wbg. Filters raw RS232 noise ensuring only stable weight signals are captured." }, { icon: "calculate", title: "Algorithm & Adjustment", text: "Automatically calculates per-piece net weight. Applies dynamic ADJ tolerance logic." }, { icon: "lan", title: "ERP Bridge Automation", text: "Pushes 100% correct bundle weight directly into LightHouse ERP, reducing 500-700 minutes of daily manual data entry." }], details: ["Integrated physical weight meters with LightHouse ERP via Serial Port communication", "Automated bundle packing workflow, reducing packing time by 60%", "Scaled daily label output from 2,500 to 8,000+ labels", "Delivered robust solution improving operational efficiency and minimizing manual errors"], date: "2026-04-01" },
    "weight-scale": { title: "YAOHUA Digital Weight Scale Integration", subtitle: "RS232 Hardware-to-ERP Bridge", company: "DhakaThai AlcoMaxx PLC", developer: "Md. Asaduzzaman (Aminur)", featured: true, tech: ["RS232 Protocol", "Serial Port Communication", "Hardware Integration", "ERP Bridge", "Signal Processing"], images: ["assets/images/projects/weight-scale/scale-hardware.jpg", "assets/images/projects/weight-scale/weight-scale-0.png", "assets/images/projects/weight-scale/weight-scale-ui-2.png", "assets/images/projects/weight-scale/weight-scale-api-1.png", "assets/images/projects/weight-scale/weight-scale-api-2.png", "assets/images/projects/weight-scale/weight-scale-api-3.png"], metrics: [{ value: "RS232", label: "Real-time Data Bridge" }, { value: "200ms", label: "Polling Cycle" }, { value: "1,500+", label: "Die Profiles" }, { value: "100%", label: "Accurate ERP Push" }], abstract: "Industrial hardware integration project connecting YAOHUA XK3190-D# digital weight indicators to LightHouse ERP via RS232 serial communication.", flow: [{ icon: "hardware", title: "Hardware Setup", text: "Configured YAOHUA XK3190-D# weight indicators with RS232 serial communication." }, { icon: "graphic_eq", title: "Signal Processing", text: "Implemented 200ms polling cycle on scale I/O, filtering raw RS232 noise." }, { icon: "memory", title: "Data Validation", text: "Validated captured weights against 1,500+ master die profiles." }, { icon: "lan", title: "ERP Push", text: "Pushed 100% accurate bundle weights directly into LightHouse ERP." }], details: ["RS232 serial communication with YAOHUA XK3190-D# digital weight indicators", "200ms polling cycle with noise filtering for stable weight capture", "Validation against 1,500+ master die profiles", "Automatic ERP data push eliminating manual entry", "Reduced daily data entry bottlenecks by 500-700 minutes"], date: "2025-02-01" },
    "tuition-management": { title: "Tuition Management System", subtitle: "Student & Fee Management Desktop App", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["C#", "SQL Server Local DB", "Windows Forms"], images: ["assets/images/placeholder.png"], metrics: [{ value: "3+", label: "Modules" }, { value: "Easy", label: "Batch Management" }], abstract: "A desktop application for managing tuition center operations including student information, fee collection, and batch management.", flow: [{ icon: "person", title: "Student Management", text: "Add, edit, and manage student profiles." }, { icon: "payments", title: "Fee Management", text: "Track monthly fee collections, generate receipts." }, { icon: "groups", title: "Batch Management", text: "Organize students into batches." }], details: ["Complete CRUD operations for student records", "Automated fee tracking with due date alerts", "Search and filter", "Export reports to Excel"], date: "2016-09-01" },
    "auto-bell": { title: "Auto Bell 2.0", subtitle: "Automated School Bell System with TTS", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["VB.net", "MS Access DB", "Text-to-Speech"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Auto", label: "Schedule-based" }, { value: "TTS", label: "Voice Announcements" }], abstract: "An automated bell system for schools that rings bells and makes voice announcements based on predefined schedules.", flow: [{ icon: "schedule", title: "Schedule Management", text: "Configure bell schedules." }, { icon: "record_voice_over", title: "Text-to-Speech", text: "Announce class changes using TTS." }], details: ["Customizable bell schedules", "Voice announcements", "Manual override", "System tray operation"], date: "2017-04-01" },
    "tic-warehouse": { title: "TIC Warehouse App", subtitle: "Inventory Management System", company: "TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["PHP", "MySQL", "Bootstrap", "jQuery"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Inventory", label: "Real-time Tracking" }, { value: "Web-based", label: "Cloud Access" }], abstract: "A web-based warehouse inventory management system for TIC Accessories Inc.", flow: [{ icon: "inventory_2", title: "Stock Management", text: "Track inventory items." }, { icon: "receipt_long", title: "Purchase Orders", text: "Generate and manage POs." }, { icon: "assessment", title: "Reports", text: "View inventory reports." }], details: ["Complete CRUD for inventory", "Real-time stock tracking", "Purchase order generation", "Responsive web interface"], date: "2020-06-01" },
    "easy-c-ide": { title: "Easy C IDE", subtitle: "Lightweight C Compiler IDE with Auto-Save", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["VB.net", "C Compiler Integration", "Windows Forms"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Lightweight", label: "< 5 MB" }, { value: "Auto-save", label: "Built-in" }], abstract: "A lightweight C programming IDE with integrated C compiler.", flow: [{ icon: "edit_note", title: "Code Editor", text: "Write C code." }, { icon: "terminal", title: "Compiler Integration", text: "Compile and run." }, { icon: "save", title: "Auto-Save", text: "Auto-saves periodically." }], details: ["Integrated C compiler", "Auto-save feature", "Lightweight (< 5 MB)", "Beginner-friendly"], date: "2016-03-01" },
    "resq-remote": { title: "Res-Q Robotic Car & Remote Control", subtitle: "Robotic Car with Desktop Control Application", company: "BPI College Projects Fair 2017 - Champion", developer: "Md. Asaduzzaman (Aminur)", tech: ["C/C++", "Arduino", "C#", "Serial Communication", "Firmware Development"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Champion", label: "BPI Projects Fair 2017" }, { value: "Dual", label: "Firmware + Desktop App" }], abstract: "An award-winning robotic car project that won Champion at BPI College Projects Fair 2017.", flow: [{ icon: "memory", title: "Arduino Firmware", text: "C/C++ firmware on Arduino." }, { icon: "desktop_windows", title: "Desktop Controller", text: "C# Windows Forms application." }, { icon: "bluetooth", title: "Communication", text: "Wireless serial communication." }], details: ["Arduino-based robotic car", "C# desktop controller", "Wireless communication", "Champion award BPI 2017"], date: "2017-03-01" },
    "faith-it": { title: "Faith IT - Agency Portfolio", subtitle: "Corporate Agency Website", company: "Faith Media Ltd.", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "Elementor", "WooCommerce", "SEO"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Live", label: "faithmedia.com" }, { value: "Agency", label: "Portfolio Site" }], abstract: "A professional agency portfolio website for Faith Media Ltd.", flow: [{ icon: "web", title: "Portfolio Showcase", text: "Visually rich portfolio." }, { icon: "search", title: "SEO Optimization", text: "On-page SEO." }, { icon: "devices", title: "Responsive Design", text: "Optimized for all devices." }], details: ["WordPress + Elementor", "Portfolio showcase", "SEO-optimized", "Contact form"], date: "2020-02-01" },
    "gontobbo-express": { title: "Gontobbo Express", subtitle: "Logistics Platform Implementation", company: "Freelance Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "WooCommerce", "Custom Plugins", "Logistics API"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Logistics", label: "Delivery Platform" }, { value: "Integrated", label: "Payment + Tracking" }], abstract: "Implementation of a logistics platform for managing deliveries.", flow: [{ icon: "local_shipping", title: "Delivery Management", text: "End-to-end delivery management." }, { icon: "track_changes", title: "Shipment Tracking", text: "Real-time tracking." }, { icon: "payments", title: "Payment Integration", text: "Integrated payment gateway." }], details: ["WooCommerce logistics", "Real-time tracking", "Payment gateway", "Admin dashboard"], date: "2021-01-01" },
    "chembynavid": { title: "ChemByNavid", subtitle: "E-Commerce & LMS Integration", company: "Freelance Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "WooCommerce", "LMS Plugin", "Content Management"], images: ["assets/images/placeholder.png"], metrics: [{ value: "E-Commerce", label: "Online Store" }, { value: "LMS", label: "Course Platform" }], abstract: "A combined e-commerce and learning management system.", flow: [{ icon: "shopping_cart", title: "E-Commerce", text: "WooCommerce store." }, { icon: "school", title: "LMS Integration", text: "Course creation." }, { icon: "sync", title: "Content Updates", text: "Content updates." }], details: ["WooCommerce e-commerce", "LMS integration", "Payment gateway", "Content maintenance"], date: "2021-02-15" },
    "rapid-supplies": { title: "Rapid Supplies Inc.", subtitle: "Tech E-Commerce Store", company: "TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "WooCommerce", "Product Management", "SEO"], images: ["assets/images/placeholder.png"], metrics: [{ value: "B2B", label: "Wholesale Platform" }, { value: "Tech", label: "Accessories Store" }], abstract: "A B2B/B2C e-commerce platform for TIC Accessories Inc.", flow: [{ icon: "category", title: "Product Catalog", text: "Organized product listings." }, { icon: "inventory", title: "Inventory Sync", text: "Real-time inventory." }, { icon: "local_shipping", title: "Order Fulfillment", text: "Automated order processing." }], details: ["WooCommerce store", "B2B bulk ordering", "Real-time inventory", "SEO-optimized"], date: "2020-07-01" },
    "different-cafe": { title: "DifferentCafeBD", subtitle: "Cafe Brand Website", company: "Freelance Project", developer: "Md. Asaduzzaman (Aminur)", url: "https://differentcafebd.com", tech: ["WordPress", "Elementor", "Branding", "Local Business SEO"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Cafe", label: "Brand Website" }, { value: "Local SEO", label: "Google Maps Ready" }], abstract: "A cafe brand website for DifferentCafeBD.", flow: [{ icon: "restaurant_menu", title: "Menu Display", text: "Digital menu." }, { icon: "location_on", title: "Location & Hours", text: "Store locations." }, { icon: "shopping_bag", title: "Online Ordering", text: "Online ordering system." }], details: ["Elementor responsive design", "Digital menu with ordering", "Local SEO", "Contact info with maps"], date: "2021-02-20" },
    "realcafe-bd": { title: "RealCafeBd", subtitle: "Cafe Brand Website", company: "Freelance Project", developer: "Md. Asaduzzaman (Aminur)", url: "https://realcafebd.com", tech: ["WordPress", "Elementor", "Branding", "Local Business SEO"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Cafe", label: "Brand Website" }, { value: "Local SEO", label: "Google Maps Ready" }], abstract: "A cafe brand website for RealCafeBd.", flow: [{ icon: "restaurant_menu", title: "Menu Display", text: "Digital menu." }, { icon: "location_on", title: "Location & Hours", text: "Store locations." }, { icon: "shopping_bag", title: "Online Ordering", text: "Online ordering system." }], details: ["Elementor responsive design", "Digital menu with ordering", "Local SEO", "Contact info with maps"], date: "2021-02-26" },
    "cosmicshopbd": { title: "CosmicShopBd", subtitle: "Website + Android E-Commerce App", company: "Freelance Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "WooCommerce", "Android", "Java", "REST API", "Multi-price", "Inventory"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Website", label: "WooCommerce Store" }, { value: "Android", label: "Native Shopping App" }], abstract: "A full-stack e-commerce solution combining WooCommerce website with native Android app.", flow: [{ icon: "store", title: "Retail Storefront", text: "Standard retail shopping." }, { icon: "warehouse", title: "Wholesale Portal", text: "Bulk ordering with tiered pricing." }, { icon: "price_change", title: "Multi-Price System", text: "Role-based price switching." }, { icon: "storefront", title: "Android App Browsing", text: "Browse products on mobile." }, { icon: "shopping_cart", title: "Android App Checkout", text: "Cart management and checkout." }, { icon: "sync", title: "API Integration", text: "Real-time data sync via REST API." }], details: ["WordPress + WooCommerce dual-mode retail/wholesale", "Native Android app with Material Design", "Multi-tier pricing", "Seamless website-app sync"], date: "2024-09-01" },
    "amazon-ebay-listings": { title: "Amazon/eBay Product Listing Suite", subtitle: "200+ SEO-Optimized E-Commerce Listings", company: "TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["Photoshop", "Illustrator", "Amazon Seller Central", "eBay Seller Hub", "SEO", "Keyword Research"], images: ["assets/images/placeholder.png"], metrics: [{ value: "200+", label: "Products Listed" }, { value: "SEO", label: "Optimized Content" }, { value: "B2B/B2C", label: "Dual Marketplace" }], abstract: "Managed and optimized 200+ product listings across Amazon and eBay.", flow: [{ icon: "photo_camera", title: "Product Photography", text: "Professional photos for marketplace." }, { icon: "edit", title: "Listing Content", text: "SEO-optimized titles and descriptions." }, { icon: "trending_up", title: "Performance", text: "Monitor and optimize analytics." }], details: ["200+ listings on Amazon and eBay", "SEO-optimized content", "Professional photography", "Competitive pricing analysis"], date: "2020-01-01" },
    "infographic-banner": { title: "E-Commerce Infographic & Banner Portfolio", subtitle: "Promotional & Social Media Visuals", company: "TIC Accessories Inc. / Freelance", developer: "Md. Asaduzzaman (Aminur)", tech: ["Photoshop", "Illustrator", "Canva", "Filmora", "Social Media Design"], images: ["assets/images/placeholder.png"], metrics: [{ value: "50+", label: "Banners Created" }, { value: "Multi-brand", label: "Design Systems" }], abstract: "Designed infographics, banners, social media visuals, and email graphics.", flow: [{ icon: "lightbulb", title: "Concept", text: "Brand guidelines and goals." }, { icon: "brush", title: "Design", text: "Create with Photoshop/Illustrator." }, { icon: "campaign", title: "Delivery", text: "Multi-format delivery." }], details: ["Sale banners and promotions", "Product comparison infographics", "Social media visuals", "Email marketing graphics"], date: "2020-04-01" },
    "label-packaging": { title: "Product Label & Barcode Print", subtitle: "Industrial & Retail Label Solutions", company: "DhakaThai AlcoMaxx PLC / TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["Photoshop", "Illustrator", "Label Design", "Barcode Systems", "Print Production"], images: ["assets/images/placeholder.png"], metrics: [{ value: "50+", label: "Label Designs" }, { value: "8,000/day", label: "Label Output" }], abstract: "Designed product labels for industrial and retail products.", flow: [{ icon: "straighten", title: "Label Layout", text: "Design with barcodes and QR." }, { icon: "print", title: "Print Production", text: "Print-ready files." }, { icon: "inventory", title: "System Integration", text: "ERP-integrated templates." }], details: ["Labels with barcodes and QR", "Shipping and warehouse labels", "Packaging design", "ERP-integrated templates"], date: "2025-10-01" },
    "barcode-label-system": { title: "Barcode & QR Label Systems", subtitle: "ERP-Integrated Label Workflows", company: "DhakaThai AlcoMaxx PLC / Keya Group", developer: "Md. Asaduzzaman (Aminur)", tech: ["Barcode Design", "QR Code Systems", "ERP Integration", "Label Printers", "RFID Tags"], images: ["assets/images/placeholder.png"], metrics: [{ value: "8,000+/day", label: "QR Labels Scaled" }, { value: "60%", label: "Speed Increase" }], abstract: "Designed barcode and QR label systems integrated with ERP workflows.", flow: [{ icon: "qr_code_scanner", title: "Label Generation", text: "Automated from ERP data." }, { icon: "sync", title: "ERP Bridge", text: "Real-time data from ERP." }, { icon: "print", title: "High-Volume Printing", text: "Continuous high-speed output." }], details: ["Scaled from 2,500 to 8,000+ daily", "Integrated with LightHouse ERP", "RFID tag generation", "Bundle QR tracking"], date: "2025-10-01" },
    "tic-accessories": { title: "TIC Accessories Inc. - Full-Spectrum Digital Operations", subtitle: "IT Support, Web Dev, E-Commerce, Design & Listings", company: "TIC Accessories Inc. (New York, USA)", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "WooCommerce", "Amazon Seller Central", "eBay", "Photoshop", "Illustrator", "Remote IT Support", "SEO", "Inventory Management"], images: ["assets/images/placeholder.png"], metrics: [{ value: "200+", label: "Product Listings" }, { value: "Full Stack", label: "Design + Dev + IT" }], abstract: "Comprehensive digital operations support for a New York-based tech accessories company.", flow: [{ icon: "support_agent", title: "Remote IT Support", text: "Via Anydesk and TeamViewer." }, { icon: "web", title: "Website Management", text: "WordPress + WooCommerce." }, { icon: "shopping_cart", title: "E-Commerce Operations", text: "Amazon + eBay management." }, { icon: "palette", title: "Design & Photography", text: "Infographics and product photos." }, { icon: "assignment", title: "Operations", text: "Excel reports and email campaigns." }], details: ["Remote IT support for NY office", "WordPress/WooCommerce website", "200+ Amazon/eBay listings", "Infographic and banner design", "Product photography editing", "Excel automation and email marketing"], date: "2020-02-01" },
    "tic-website": { title: "TIC Accessories - Corporate Website", subtitle: "WordPress Company Site with WooCommerce", company: "TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["WordPress", "Elementor", "WooCommerce", "Product Management", "Contact System"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Corporate", label: "Brand Presence" }, { value: "E-Commerce", label: "Integrated Store" }], abstract: "Main company website for TIC Accessories Inc. on WordPress with Elementor.", flow: [{ icon: "web", title: "Site Architecture", text: "Responsive WordPress site." }, { icon: "category", title: "Product Catalog", text: "Organized product catalog." }, { icon: "shopping_cart", title: "WooCommerce Store", text: "Integrated online store." }], details: ["WordPress + Elementor", "WooCommerce integration", "Product catalog with search", "Contact forms"], date: "2020-03-01" },
    "tasbih": { title: "Tasbih - Digital Prayer Counter", subtitle: "Android Tasbih Counting App", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["MIT App Inventor", "Android", "TinyDB"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Android", label: "Mobile App" }, { value: "Offline", label: "No Internet Needed" }], abstract: "A digital tasbih (prayer bead) counter Android app.", flow: [{ icon: "touch_app", title: "Tap Counting", text: "Simple tap interface." }, { icon: "bookmark", title: "Multiple Profiles", text: "Different prayer counters." }, { icon: "history", title: "History Tracking", text: "Daily/weekly/monthly views." }], details: ["Material Design interface", "Multiple counter profiles", "Session history", "Offline operation"], date: "2024-10-01" },
    "zenbreaths": { title: "ZenBreaths - Guided Breathing App", subtitle: "Cross-Platform Mindfulness App", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["HTML", "Tailwind CSS", "Vue 3", "Nuxt", "Capacitor", "Android Studio"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Guided", label: "Breathing Sessions" }, { value: "Custom", label: "Duration Settings" }], abstract: "A cross-platform guided breathing and meditation app.", flow: [{ icon: "air", title: "Breathing Exercises", text: "Visual inhale/hold/exhale." }, { icon: "timer", title: "Session Control", text: "Customizable duration." }, { icon: "music_note", title: "Ambient Sounds", text: "Optional background sounds." }], details: ["Visual breathing animation", "1-30 min session duration", "Ambient sounds", "Session history"], date: "2026-02-01" },
    "hakimadapp-website": { title: "Hakimadapp.github.io - Religious Website", subtitle: "Faith-Based Islamic Website", company: "Personal Project", developer: "Md. Asaduzzaman (Aminur)", tech: ["HTML", "CSS", "JavaScript", "GitHub Pages"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Religious", label: "Faith Platform" }, { value: "Responsive", label: "All Devices" }], abstract: "A religious/faith-based website hosted on GitHub Pages.", flow: [{ icon: "menu_book", title: "Content Sections", text: "Organized religious content." }, { icon: "public", title: "Global Access", text: "GitHub Pages hosting." }, { icon: "devices", title: "Responsive Design", text: "Mobile, tablet, desktop." }], details: ["Faith-based content", "HTML/CSS/JS", "GitHub Pages", "Responsive design"], date: "2026-03-01" },
    "dhakathai-it": { title: "DhakaThai Alcomaxx PLC - IT Operations", subtitle: "Barcode Station Support for Aluminum Manufacturing Plant", company: "DhakaThai AlcoMaxx PLC", developer: "Md. Asaduzzaman (Aminur)", tech: ["IT Support", "OS Administration", "Barcode ERP", "System Maintenance", "Tools Development", "Network Setup"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Plant-wide", label: "IT Operations" }, { value: "ERP", label: "Barcode Integration" }], abstract: "Managed Barcode Station operations at an aluminum manufacturing plant.", flow: [{ icon: "dns", title: "System Administration", text: "Windows/Linux systems." }, { icon: "inventory", title: "Barcode ERP", text: "Labeling ERP systems." }, { icon: "build", title: "Tools Development", text: "Utility tools for automation." }, { icon: "router", title: "Network & Hardware", text: "LAN, printers, peripherals." }], details: ["IT support for manufacturing plant", "OS administration", "Barcode ERP management", "Tool development", "Network configuration"], date: "2023-08-01" },
    "keya-group-it": { title: "Keya Group [IT-GPRO] - ERP Administration", subtitle: "IT Support Across 50+ Workstations", company: "Keya Knit Composite Ltd.", developer: "Md. Asaduzzaman (Aminur)", tech: ["GPRO ERP", "IT Support", "OS Administration", "RFID Systems", "Barcode Systems", "Network Maintenance", "User Training"], images: ["assets/images/placeholder.png"], metrics: [{ value: "50+", label: "Workstations Managed" }, { value: "20+", label: "Users Trained" }], abstract: "Administered IT operations at Gpro Section of Keya Group, a large RMG factory.", flow: [{ icon: "storage", title: "GPRO ERP", text: "Managed ERP modules." }, { icon: "desktop_windows", title: "Workstations", text: "50+ PCs and printers." }, { icon: "qr_code_scanner", title: "RFID & Barcode", text: "RFID tags and barcode systems." }, { icon: "school", title: "User Training", text: "Trained 20+ employees." }], details: ["GPRO ERP administration", "50+ workstation management", "RFID and barcode systems", "User training (20+ staff)"], date: "2022-06-01" },
    "bpi-lab": { title: "B. P. I. Innovation Lab", subtitle: "College Innovation Lab Setup & Support", company: "Bogura Polytechnic Institute", developer: "Md. Asaduzzaman (Aminur)", tech: ["Hardware Setup", "Software Installation", "Network Configuration", "Lab Maintenance"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Lab Setup", label: "Full Installation" }, { value: "Multi-Use", label: "Software + Hardware" }], abstract: "Set up and maintained the Innovation Lab at Bogura Polytechnic Institute.", flow: [{ icon: "computer", title: "Hardware Setup", text: "Assembled computer systems." }, { icon: "code", title: "Software Installation", text: "Development tools and IDEs." }, { icon: "lan", title: "Network Configuration", text: "Local network with internet." }], details: ["Hardware setup and configuration", "Software installation", "Network setup", "Ongoing maintenance"], date: "2018-03-01" },
    "naogaon-lab": { title: "Naogaon Tech. School ICT Lab", subtitle: "Computer Lab Installation for Technical School", company: "Naogaon Technical School & College", developer: "Md. Asaduzzaman (Aminur)", tech: ["PC Assembly", "OS Installation", "Software Setup", "Hardware Diagnostics"], images: ["assets/images/placeholder.png"], metrics: [{ value: "Lab Setup", label: "Complete Installation" }, { value: "ICT", label: "Curriculum Ready" }], abstract: "Set up the ICT computer lab at Naogaon Technical School & College.", flow: [{ icon: "build", title: "PC Assembly", text: "Assembled from components." }, { icon: "desktop_windows", title: "OS & Software", text: "Windows and Linux install." }, { icon: "bug_report", title: "Diagnostics", text: "Hardware troubleshooting." }], details: ["PC assembly", "OS installation", "Educational software", "Hardware diagnostics"], date: "2012-09-01" },
    "dtl-google-chrome": { title: "DTL - Portable Google Chrome (No CORS)", subtitle: "Cross-Origin Development Environment", company: "DhakaThai AlcoMaxx PLC / TIC Accessories Inc.", developer: "Md. Asaduzzaman (Aminur)", tech: ["Portable Chrome", "Batch Scripting", "CORS Bypass Config", "User Data Management"], images: ["assets/images/projects/dtl-google-chrome/screenshot.png"], metrics: [{ value: "No CORS", label: "Dev Environment" }, { value: "Portable", label: "No Install Needed" }], abstract: "Configured a portable Google Chrome with custom user data directory disabling CORS.", flow: [{ icon: "public", title: "No-CORS Browsing", text: "Chrome with --disable-web-security." }, { icon: "usb", title: "Portable Setup", text: "Runs from USB drive." }, { icon: "terminal", title: "Batch Automation", text: "One-click launch script." }], details: ["Portable Chrome no-CORS", "Custom user data directory", "Batch script launcher", "No installation needed"], date: "2026-05-01" }
  },
  multimediaCategories: [
    { name: "Creative Services", key: "creative", icon: "auto_awesome", items: [
      { id: "custom-poetry-01", title: "Custom Poetry Composition", description: "Personalized poetry for events, presentations, and media projects.", date: "2026-05-01" },
      { id: "custom-song-01", title: "Original Song Production", description: "Custom song with personalized lyrics and AI-assisted composition.", date: "2026-04-15" },
      { id: "ai-video-01", title: "AI-Powered Promotional Video", description: "End-to-end video with AI-generated visuals and animation.", date: "2026-06-01" },
      { id: "pencil-portrait-01", title: "Pencil Portrait from Photo", description: "Hand-drawn realistic pencil portrait from reference photo.", date: "2026-03-10" },
      { id: "home-decor-01", title: "Custom Wall Art Design", description: "AI-designed wall-framed picture with personalized theme.", date: "2026-05-20" },
      { id: "brand-guide-01", title: "Brand Identity & Style Guide", description: "Complete brand identity package.", date: "2026-02-15" }
    ]},
    { name: "Graphics & Design", key: "design", icon: "palette", items: [
      { id: "amazon-listings", title: "Amazon/eBay Product Listings (200+)", description: "Designed 200+ SEO-friendly product listings.", date: "2020-01-01" },
      { id: "infographic-banners", title: "Infographic & Banner Design", description: "Sales banners and social media visuals.", date: "2020-04-01" },
      { id: "label-packaging", title: "Product Label & Packaging Design", description: "Labels and packaging for industrial products.", date: "2025-10-01" },
      { id: "barcode-label-system", title: "Barcode & QR Label Systems", description: "ERP-integrated barcode and QR label systems.", date: "2025-10-01" }
    ]},
    { name: "Video & Multimedia", key: "video", icon: "videocam", items: [
      { id: "weight-checker-video", title: "Weight Checker App Demo", description: "Demonstration of automated bundle weight checking system.", date: "2026-04-01" },
      { id: "wedding-slideshow", title: "Wedding Presentation Video", description: "Custom wedding presentation with photo montage.", date: "2026-05-15" },
      { id: "product-promo", title: "Product Promotional Reel", description: "Short-form promotional video for social media.", date: "2026-03-20" }
    ]},
    { name: "Photography", key: "photo", icon: "camera_alt", items: [
      { id: "product-photography", title: "E-Commerce Product Photography", description: "Professional product photography for marketplace listings.", date: "2020-03-01" },
      { id: "event-coverage", title: "Event Photography Coverage", description: "Event photography with editing and color grading.", date: "2025-12-01" }
    ]}
  ],
  servicesGroups: [
    { icon: "laptop_mac", title: "Web & App Development", bg: "var(--primary)", chipColor: "var(--primary-light)", borderLeft: "3px solid var(--primary)", items: [
      { icon: "web", title: "Web Development & CMS", description: "Custom WordPress, WooCommerce, Vue, and Laravel development.", highlights: ["WordPress, Elementor, WooCommerce", "Vue 3 SPA Development", "Laravel REST API & Backend", "Custom Theme & Plugin Development", "Payment Gateway Integration, LMS, ACF", "SEO Optimization & Performance Tuning"] },
      { icon: "important_devices", title: "Hybrid Mobile App (PWA, Web, Android)", description: "Cross-platform mobile solutions combining PWA and Capacitor.", highlights: ["Progressive Web App (PWA) Development", "Hybrid Android APK via Capacitor", "Vue 3 / React + Capacitor Integration", "Offline Mode, Push Notifications & Service Workers", "Play Store Deployment & App Updates", "Camera, GPS & Native Plugin Access"] },
      { icon: "code", title: "Custom Software & Tools Development", description: "Bespoke desktop applications, internal business tools, and automation scripts.", highlights: ["Bespoke Desktop Applications", "Internal Business & Productivity Tools", "Utility Software & CLI Tools", "Process Automation Scripts", "C# .NET WinForms & ADO.NET", "System Integration & Custom Reporting"] }
    ]},
    { icon: "support", title: "IT & Business Support", bg: "var(--primary)", chipColor: "var(--primary-light)", borderLeft: "3px solid var(--primary)", items: [
      { icon: "dns", title: "Software & Hardware Troubleshooting & IT Support", description: "Full-spectrum PC troubleshooting and IT support.", highlights: ["Windows OS Installation, Repair & Recovery", "Hardware Diagnostics: RAM, HDD/SSD, PSU, Motherboard", "Driver Conflict Resolution & Peripheral Setup", "Slow PC Optimization & Malware Removal", "Data Backup, Recovery & System Migration", "PC Assembly, Upgrade & Remote IT Support"] },
      { icon: "settings_applications", title: "ERP & Business Systems Administration", description: "Full-cycle ERP management including module configuration, data entry, payroll, inventory, POS.", highlights: ["ERP Module Configuration & Management", "Inventory, Payroll & Billing Operations", "POS Systems & Data Entry", "File Handling & Document Management", "ERP Install, Migration & Support", "Garments Systems & RFID Tag Generation"] },
      { icon: "lan", title: "Network Infrastructure & Security", description: "Basic network services — IP configuration, LAN/router setup, printer sharing, firewall.", highlights: ["Laptop / PC IP Configuration & Troubleshooting", "LAN / Router Setup & Network Configuration", "File & Printer Sharing Setup", "Firewall & Antivirus Deployment", "Network Device Diagnostics & Maintenance", "PC / Printer Network Troubleshooting"] }
    ]},
    { icon: "trending_up", title: "E-Commerce & Marketing", bg: "var(--primary)", chipColor: "var(--primary-light)", borderLeft: "3px solid var(--primary)", items: [
      { icon: "shopping_cart", title: "E-Commerce & Online Store Solutions", description: "Full WooCommerce store development on WordPress.", highlights: ["WooCommerce Store Development on WordPress", "Theme Customization & Product Catalog Setup", "Product Photography, Editing & Infographics", "Order, Shipping & Inventory Management", "Promotional Email Campaigns & Newsletters", "Store Maintenance & Performance Optimization"] },
      { icon: "campaign", title: "Email Marketing & Campaigns", description: "End-to-end email campaign management.", highlights: ["Campaign Setup & Automation", "Newsletter & Lead Nurture Sequences", "Bulk Mailing Tools (Mailchimp, SendGrid)", "Email Copywriting & Analytics", "Subscriber List Management & Segmentation", "A/B Testing & Performance Reporting"] },
      { icon: "webhook", title: "Email & Web Template Design", description: "Custom-coded HTML email templates and responsive web page templates.", highlights: ["HTML Email Template Design & Coding", "Responsive Email Layouts (Dark Mode Ready)", "Landing Page & Web Template Design", "Mailchimp / SendGrid Template Integration", "Brand-consistent Visual Email Design", "Cross-client Email Rendering Testing"] }
    ]},
    { icon: "auto_awesome", title: "Design & Multimedia", bg: "var(--primary)", chipColor: "var(--primary-light)", borderLeft: "3px solid var(--primary)", items: [
      { icon: "palette", title: "Graphic Design & Branding", description: "Professional print and digital design.", highlights: ["Business Cards, Flyers & Banners", "Social Media Posts & Cover Art", "Product Photography & Editing", "Infographics, Labels & Invoices", "Logo & Brand Identity Design", "Brochures, Menus & Print-ready Artwork"] },
      { icon: "videocam", title: "Video Editing", description: "Creative video editing for social media reels and promotional clips.", highlights: ["Short-form Reels & Social Media Clips", "Promotional & Corporate Video Editing", "Trimming, Transitions & Color Grading", "Text Overlays, Captions & Titles", "Background Music & Audio Sync", "CapCut & Mobile-first Video Optimization"] },
      { icon: "movie_creation", title: "AI-Powered Multimedia Production", description: "End-to-end multimedia content created with AI.", highlights: ["AI Comic Strip & Cartoon Generation", "AI Digital Art & Image Compositing", "AI Photo Retouching & Manipulation", "AI Audio Editing & Voiceover Production", "AI Music Composition & Background Scoring", "AI Animation & Motion Graphics"] }
    ]},
    { icon: "psychology", title: "AI Services", bg: "var(--primary)", chipColor: "var(--primary-light)", borderLeft: "3px solid var(--primary)", items: [
      { icon: "description", title: "AI Writing & Document Help", description: "Practical AI-powered writing for everyday needs.", highlights: ["Resume & Cover Letter Writing", "Official Email & Letter Drafting", "Job Application & Proposal Writing", "Report & Document Formatting", "Proofreading & Paraphrasing", "Multi-language Translation"] },
      { icon: "auto_awesome", title: "AI Image & Photo Services", description: "Real-world image solutions — product photos, portrait retouching.", highlights: ["Product Photo Editing & Retouching", "Background Removal & Replacement", "Old Photo Restoration & Colorization", "Passport & ID Photo Processing", "AI Portrait & Profile Picture Creation", "Social Media Visual & Thumbnail Design"] },
      { icon: "smart_toy", title: "AI Automation & Chatbot Setup", description: "Practical automation for small businesses.", highlights: ["AI Customer Reply Chatbot Setup", "Automated Email & Message Responses", "Data Entry & Spreadsheet Automation", "PDF Data Extraction & Processing", "Social Media Auto-Reply & Scheduling", "Simple n8n Workflow Automation"] }
    ]},
    { icon: "brush", title: "Creative Services — Powered by A.I.", note: "AI-assisted creative works — content, design, print, and branding deliverables.", bg: "var(--accent-purple)", chipColor: "var(--accent-purple)", borderLeft: "3px solid var(--accent-purple)", items: [
      { icon: "edit_note", title: "Custom Poetry & Voice", description: "Personalized poetry and spoken-word content.", highlights: ["Custom Poetry for Events & Occasions", "Voice-Recorded Spoken Word", "Presentation & Script Writing", "Multi-language Poetry Options", "Themed & Branded Content", "Quick Turnaround Delivery"] },
      { icon: "music_note", title: "Custom Songs & Music Production", description: "Original songs with personalized lyrics and AI-assisted composition.", highlights: ["Personalized Lyrics & Composition", "AI-Assisted Music Production", "Wedding & Event Presentation Songs", "Brand Campaign Audio Content", "Full Audio + Video Output", "Customizable Genre & Style"] },
      { icon: "videocam", title: "AI Video Content Creation", description: "Video content from concept to final edit with AI-powered visuals.", highlights: ["Content Planning & Storyboarding", "AI-Generated Visuals & Animation", "Photo Montage & Slideshow Videos", "Voiceover & Background Music Sync", "Social Media-Ready Short Clips", "Professional Editing & Color Grading"] },
      { icon: "gesture", title: "Pencil Sketch & Portrait Art", description: "Hand-drawn pencil portraits from reference photos.", highlights: ["Portrait Sketch from Photo Reference", "Realistic Pencil Drawing on Paper", "Custom Size & Framing Options", "Gift-Ready Packaged Artwork", "AI-Enhanced Photo Reference Prep", "Digital Scan Copy Included"] },
      { icon: "wallpaper", title: "AI Home Decor Design", description: "Custom wall art and decor designs created with AI.", highlights: ["Custom Wall-Framed Picture Design", "AI-Generated Canvas & Print Art", "Personalized Quote & Name Frames", "Custom Size & Aspect Ratio Options", "Theme-Based Decor Collections", "Printable & Ready-to-Frame Formats"] },
      { icon: "store", title: "Custom Stationery & Branding", description: "Bespoke stationery sets, t-shirt graphics, brand identity guides.", highlights: ["Custom Stationery Sets Design", "T-Shirt Graphics & Print-Ready Art", "Brand Identity & Style Guide Creation", "Logo, Business Card & Letterhead Sets", "Packaging & Label Design", "Full Merchandise Design Suite"] }
    ]},
    { icon: "precision_manufacturing", title: "Industrial & On-Site", note: "Specialized services for manufacturing environments — available for on-site work.", bg: "var(--accent-amber)", chipColor: "var(--accent-amber)", borderLeft: "3px solid var(--accent-amber)", items: [
      { icon: "storage", title: "Desktop Automation & Hardware Integration", description: "Custom C# .NET desktop applications integrated with industrial hardware.", highlights: ["C# .NET WinForms & ADO.NET Applications", "YAOHUA Digital Weight Scale Integration", "Automated Label & Barcode Printing Systems", "Serial Port & Hardware Communication", "Crystal Reports & Data Export Solutions", "Excel VBA Macros & Process Automation"] },
      { icon: "settings_ethernet", title: "Industrial RFID, Barcode & IoT Systems", description: "Production floor data collection infrastructure.", highlights: ["RFID NXP MCU Terminal Setup & Management", "MOXA Multiport Serial Card Configuration", "RJ-6 (RS-485) Cabling & Infrastructure", "Barcode Printer Configuration & Label Automation", "Production Floor RFID Checkpoints & Data Collection", "ERP-to-Floor Device Integration (MOXA / RFID)"] },
      { icon: "dns", title: "Production Floor IT & Systems Support", description: "IT support tailored for manufacturing environments.", highlights: ["PC / Printer Setup & Troubleshooting on Production Floor", "LAN, IP Config & Network Diagnostics", "ERP User Administration & Module Support", "File & Printer Sharing for Workshop Environments", "30+ Workstation & Device Management", "RJ-6 / MOXA Device Networking & Support"] }
    ]}
  ]
};
